jobs:
  -
    job: '${{ parameters.tag }}'
    timeoutInMinutes: 0
    pool:
      vmImage: ubuntu-16.04
    dependsOn: '${{ parameters.dep }}'
    steps:
      -
        script: 'docker build -f internal/docker/${{ parameters.file }} -t ArtMares/qt:${{ parameters.tag }} .'
      -
        script: 'docker login -u therecipe -p $(DOCKER_PASSWORD) && docker push ArtMares/qt:${{ parameters.tag }} && docker logout'
